version: "3"

services:
  db:
    image: postgres:alpine
    container_name: pgsql_container
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=social_db
    ports:
      - "5432:5432"