CREATE TABLE IF NOT EXISTS roles (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name varchar(50)
);

CREATE TABLE IF NOT EXISTS users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    username varchar(50),
    password varchar(255),
    role_id bigint,
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS bookings (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_time_booking TIMESTAMP NOT NULL,
    date_of_creation TIMESTAMP NOT NULL,
    arrived TINYINT(1),
    active TINYINT(1),
    completed TINYINT(1),
    user_id bigint,
    FOREIGN KEY (user_id) REFERENCES users(id)
);